version: '3'
services:
  postgres_project_1:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres_project_1
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./pgsql-data-1:/var/lib/postgresql/data
    ports:
      - 5433:5432
  postgres_project_2:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres_project_2
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./pgsql-data-2:/var/lib/postgresql/data
    ports:
      - 5434:5432
