version: '3'
services:
  project_1:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: project_1_db
      POSTGRES_USER: project_1_user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./pgsql-data-1:/var/lib/postgresql/data
    ports:
      - 5433:5432
  project_2:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: project_2_db
      POSTGRES_USER: project_2_user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./pgsql-data-2:/var/lib/postgresql/data
    ports:
      - 5434:5432
