kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-neko
  labels:
    type: local
    app: postgres-neko
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-neko
  labels:
    app: postgres-neko
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

# 2. kubectl create -f storage.yaml
